name: Maybe Trigger Workflows

on:
  pull_request:
    types:
      - labeled

jobs:
  maybe_run_workflows:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-label')
    steps:
      - name: Trigger other workflows
        run: |
          gh workflow run platform --ref ${{ github.event.pull_request.head.sha }}
        env:
          GH_TOKEN: ${{ github.token }}
